openapi: 3.0.0

info:
  title: 'CW2 Coursework'
  description: 'Microservice for Trail Service'
  version: '1.0.0'

servers:
  - url: '/api'

components:
  schemas:
    user:
      type: 'object'
      required:
        - user_id
        - username
        - email_address
        - role
        - password
      properties:
        user_id:
          type: 'string'
          maxlength: 6
        username:
          type: 'string'
          maxlength: 50
        email_address:
          type: 'string'
          maxlength: 20
        role:
          type: 'string'
          maxlength: 5
        password:
          type: 'string'
          maxlength: 64
    trail:
      type: 'object'
      required:
        - trail_id
        - trail_name
        - trail_summary
        - trail_description
        - difficulty
        - location
        - length
        - elevation_gain
        - route_type
        - owner_id
        - pt1_lat
        - pt1_long
        - pt2_lat
        - pt2_long
        - pt3_lat
        - pt3_long
        - pt4_lat
        - pt4_long
        - pt5_lat
        - pt5_long
      properties:
        trail_id:
          type: 'string'
          maxlength: 6
        trail_name:
          type: 'string'
          maxlength: 128
        trail_summary:
          type: 'string'
          maxlength: 255
        trail_description:
          type: 'string'
          maxlength: 255
        difficulty:
          type: 'string'
          maxlength: 8
        location:
          type: 'string'
          maxlength: 128
        length:
          type: 'float'
          minimum: 0.0
          maximum: 999.9
        elevation_gain:
          type: 'integer'
          minimum: 0
          maximum: 99999
        route_type:
          type: 'string'
          maxlength: 14
        owner_id:
          type: 'string'
          maxlength: 6
        pt1_lat:
          type: 'float'
          minimum: -90 
          maximum: 90
        pt1_long:
          type: 'float'
          minimum: -180
          maximum: 180
        pt1_desc:
          type: 'string'
          maxlength: 255
        pt2_lat:
          type: 'float'
          minimum: -90 
          maximum: 90
        pt2_long:
          type: 'float'
          minimum: -180
          maximum: 180
        pt2_desc:
          type: 'string'
          maxlength: 255
        pt3_lat:
          type: 'float'
          minimum: -90 
          maximum: 90
        pt3_long:
          type: 'float'
          minimum: -180
          maximum: 180
        pt3_desc:
          type: 'string'
          maxlength: 255
        pt4_lat:
          type: 'float'
          minimum: -90 
          maximum: 90
        pt4_long:
          type: 'float'
          minimum: -180
          maximum: 180
        pt4_desc:
          type: 'string'
          maxlength: 255
        pt5_lat:
          type: 'float'
          minimum: -90 
          maximum: 90
        pt5_long:
          type: 'float'
          minimum: -180
          maximum: 180
        pt5_desc:
          type: 'string'
          maxlength: 255
    feature:
      type: 'object'
      required:
        - trail_feature_id
        - trail_feature
      properties:
        trail_feature_id:
          type: 'string'
        trail_feature:
          type: 'string'
    trail_feature:
      type: 'object'
      required:
        - trail_id
        - trail_feature_id
      properties:
        trail_id:
          type: 'string'
        trail_feature_id:
          type: 'string'
  parameters:
    user_id:
      name: 'user_id'
      description: 'The unique ID of the user'
      in: path
      required: True
      schema:
        type: 'string'

paths:
  /user:
    get:
      operationId: 'user.read_all'
      tags:
        - 'User'
      summary: 'Reads all users'
      responses:
        '200':
          description: "Successfully read user list"
        '400':
          description: "Failed to read user list"
    post:
      operationId: 'user.create'
      tags:
        - 'User'
      summary: 'Creates a user'
      requestBody:
        description: 'User to create'
        required: True
        content:
          application/json:
            schema:
              x-body-name: 'user'
              $ref: '#/components/schemas/user'
      responses:
        '201':
          description: 'User successfully created'
        '400':
          description: 'Failed to create user'
  /user/{user_id}:
    get:
      operationId: 'user.retrieve'
      tags:
        - 'User'
      summary: 'Reads one individual user'
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: 'User read successfully'
    put:
      tags:
        - 'User'
      operationId: 'user.updatePassword'
      summary: 'Update user password'
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: 'User updated successfully'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'user'
              $ref: '#/components/schemas/user'
    put:
      tags:
        - 'User'
      operationId: 'user.updateEmail'
      summary: 'Update user email address'
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: 'User updated successfully'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'user'
              $ref: '#/components/schemas/user'
    put:
      tags:
        - 'User'
      operationId: 'user.updateUsername'
      summary: 'Update user username'
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: 'User updated successfully'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'user'
              $ref: '#/components/schemas/user'
    delete:
      tags:
        - 'User'
      operationId: 'user.delete'
      summary: 'Deletes a user'
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '204':
          description: 'User successfully deleted'
  /trail:
    get:
      operationId: 'trail.read_all'
      tags:
        - 'Trail'
      summary: 'Reads all trails'
      responses:
        '200':
          description: "Successfully read trail list"
        '400':
          description: "Failed to read trail list"
    post:
      operationId: 'trail.create'
      tags:
        - 'Trail'
      summary: 'Creates a new trail'
      requestBody:
        description: 'Trail to create'
        required: True
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
      responses:
        '201':
          description: 'Trail successfully created'
        '400':
          description: 'Failed to create trail'
  /trail/{trail_id}:
    get:
      operationId: 'trail.retrieve'
      tags:
        - 'Trail'
      summary: 'Reads one specific trail'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Trail read successfully'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updateTrailName'
      summary: 'Update trail name'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Trail name updated successfully'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updateTrailSummary'
      summary: 'Update trail summary'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Trail summary successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updateTrailDescription'
      summary: 'Update trail description'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Trail description successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updateDifficulty'
      summary: 'Update trail difficulty'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Trail difficulty successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updateLocation'
      summary: 'Update trail location'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Trail location successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updateLength'
      summary: 'Update trail length'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Trail length successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updateElevationGain'
      summary: 'Update elevation gain of trail'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Elevation gain successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updateRouteType'
      summary: 'Update route type'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Route type successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint1Longitude'
      summary: 'Update longitude of point 1'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Longitude of point 1 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint1Latitude'
      summary: 'Update latitude of point 1'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Latitude of point 1 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint1Description'
      summary: 'Update point 1 description'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Point 1 description successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint2Longitude'
      summary: 'Update longitude of point 2'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Longitude of point 2 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint2Latitude'
      summary: 'Update latitude of point 2'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Latitude of point 2 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint2Description'
      summary: 'Update point 2 description'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Point 2 description successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint3Longitude'
      summary: 'Update longitude of point 3'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Longitude of point 3 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint3Latitude'
      summary: 'Update latitude of point 3'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Latitude of point 3 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint3Description'
      summary: 'Update point 3 description'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Point 3 description successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint4Longitude'
      summary: 'Update longitude of point 4'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Longitude of point 4 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint4Latitude'
      summary: 'Update latitude of point 4'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Latitude of point 4 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint4Description'
      summary: 'Update point 4 description'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Point 4 description successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint5Longitude'
      summary: 'Update longitude of point 5'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Longitude of point 5 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint5Latitude'
      summary: 'Update latitude of point 5'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Latitude of point 5 successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.updatePoint5Description'
      summary: 'Update point 5 description'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Point 5 description successfully updated'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
    delete:
      tags:
        - 'Trail'
      operationId: 'trail.delete'
      summary: 'Deletes a trail'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '204':
          description: 'Trail successfully deleted'    
