openapi: 3.0.0

info:
  title: 'CW2 Coursework'
  description: 'Microservice for Trail Service'
  version: '1.0.0'

servers:
  - url: '/api'

components:
  schemas:
    user:
      type: 'object'
      required:
        - user_id
        - username
        - email_address
        - role
        - password
      properties:
        user_id:
          type: 'string'
          maxLength: 6
        username:
          type: 'string'
          maxLength: 50
        email_address:
          type: 'string'
          maxLength: 20
        role:
          type: 'string'
          maxLength: 5
        password:
          type: 'string'
          maxLength: 64
    authenticate:
      type: 'object'
      required:
        - email
        - password
      properties:
        email:
          type: 'string'
          maxLength: 20
        password:
          type: 'string'
          maxLength: 64
    trail:
      type: 'object'
      required:
        - trail_id
        - trail_name
        - trail_summary
        - trail_description
        - difficulty
        - location
        - length
        - elevation_gain
        - route_type
        - owner_id
        - pt1_lat
        - pt1_long
        - pt2_lat
        - pt2_long
        - pt3_lat
        - pt3_long
        - pt4_lat
        - pt4_long
        - pt5_lat
        - pt5_long
      properties:
        trail_id:
          type: 'string'
          maxLength: 6
        trail_name:
          type: 'string'
          maxLength: 128
        trail_summary:
          type: 'string'
          maxLength: 255
        trail_description:
          type: 'string'
          maxLength: 255
        difficulty:
          type: 'string'
          maxLength: 8
        location:
          type: 'string'
          maxLength: 128
        length:
          type: 'number'
          format: 'float'
          minimum: 0.0
          maximum: 999.9
        elevation_gain:
          type: 'integer'
          minimum: 0
          maximum: 99999
        route_type:
          type: 'string'
          maxLength: 14
        owner_id:
          type: 'string'
          maxLength: 6
        pt1_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt1_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt1_desc:
          type: 'string'
          maxLength: 255
        pt2_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt2_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt2_desc:
          type: 'string'
          maxLength: 255
        pt3_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt3_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt3_desc:
          type: 'string'
          maxLength: 255
        pt4_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt4_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt4_desc:
          type: 'string'
          maxLength: 255
        pt5_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt5_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt5_desc:
          type: 'string'
          maxLength: 255
    trail_update:
      type: 'object'
      required:
        - trail_name
        - trail_summary
        - trail_description
        - difficulty
        - location
        - length
        - elevation_gain
        - route_type
        - pt1_lat
        - pt1_long
        - pt2_lat
        - pt2_long
        - pt3_lat
        - pt3_long
        - pt4_lat
        - pt4_long
        - pt5_lat
        - pt5_long
      properties:
        trail_name:
          type: 'string'
          maxLength: 128
        trail_summary:
          type: 'string'
          maxLength: 255
        trail_description:
          type: 'string'
          maxLength: 255
        difficulty:
          type: 'string'
          maxLength: 8
        location:
          type: 'string'
          maxLength: 128
        length:
          type: 'number'
          format: 'float'
          minimum: 0.0
          maximum: 999.9
        elevation_gain:
          type: 'integer'
          minimum: 0
          maximum: 99999
        route_type:
          type: 'string'
          maxLength: 14
        pt1_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt1_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt1_desc:
          type: 'string'
          maxLength: 255
        pt2_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt2_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt2_desc:
          type: 'string'
          maxLength: 255
        pt3_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt3_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt3_desc:
          type: 'string'
          maxLength: 255
        pt4_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt4_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt4_desc:
          type: 'string'
          maxLength: 255
        pt5_lat:
          type: 'number'
          format: 'float'
          minimum: -90.0
          maximum: 90.0
        pt5_long:
          type: 'number'
          format: 'float'
          minimum: -180.0
          maximum: 180.0
        pt5_desc:
          type: 'string'
          maxLength: 255
    feature:
      type: 'object'
      required:
        - trail_feature_id
        - trail_feature
      properties:
        trail_feature_id:
          type: 'string'
        trail_feature:
          type: 'string'
    feature_update:
      type: 'object'
      required:
        - trail_feature
      properties:
        trail_feature:
          type: 'string'
    trail-feature:
      type: 'object'
      required:
        - trail_id
        - trail_feature_id
      properties:
        trail_id:
          type: 'string'
        trail_feature_id:
          type: 'string'
  parameters:
    user_id:
      name: 'user_id'
      description: 'The unique ID of the user'
      in: 'query'
      required: True
      schema:
        type: 'string'
    trail_id:
      name: 'trail_id'
      description: 'The unique ID of the trail'
      in: 'query'
      required: True
      schema:
        type: 'string'
    trail_feature_id:
      name: 'trail_feature_id'
      description: 'The unique ID of the trail feature'
      in: 'query'
      required: True
      schema:
        type: 'string'

paths:
  /user:
    get:
      operationId: 'user.read_all'
      tags:
        - 'User'
      summary: 'Reads all users'
      responses:
        '200':
          description: "Successfully read user list"
        '400':
          description: "Failed to read user list"
    post:
      operationId: 'user.create'
      tags:
        - 'User'
      summary: 'Creates a user'
      requestBody:
        description: 'User to create'
        required: True
        content:
          application/json:
            schema:
              x-body-name: 'user'
              $ref: '#/components/schemas/user'
      responses:
        '201':
          description: 'User successfully created'
        '400':
          description: 'Failed to create user'
  /user/{user_id}:
    get:
      operationId: 'user.retrieve'
      tags:
        - 'User'
      summary: 'Reads one individual user'
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: 'User read successfully'
    delete:
      tags:
        - 'User'
      operationId: 'user.delete'
      summary: 'Deletes a user'
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '204':
          description: 'User successfully deleted'
  /trail:
    get:
      operationId: 'trail.read_all'
      tags:
        - 'Trail'
      summary: 'Reads all trails'
      responses:
        '200':
          description: "Successfully read trail list"
        '400':
          description: "Failed to read trail list"
    post:
      operationId: 'trail.create'
      tags:
        - 'Trail'
      summary: 'Creates a new trail'
      requestBody:
        description: 'Trail to create'
        required: True
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail'
      responses:
        '201':
          description: 'Trail successfully created'
        '400':
          description: 'Failed to create trail'
  /trail/{trail_id}:
    get:
      operationId: 'trail.retrieve'
      tags:
        - 'Trail'
      summary: 'Reads one specific trail'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Trail read successfully'
    put:
      tags:
        - 'Trail'
      operationId: 'trail.update'
      summary: 'Update trail details'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '200':
          description: 'Trail details updated successfully'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'trail'
              $ref: '#/components/schemas/trail_update'
    delete:
      tags:
        - 'Trail'
      operationId: 'trail.delete'
      summary: 'Deletes a trail'
      parameters:
        - $ref: '#/components/parameters/trail_id'
      responses:
        '204':
          description: 'Trail successfully deleted'
  /feature:
    get:
      operationId: 'feature.read_all'
      tags:
        - 'Feature'
      summary: 'Reads all features'
      responses:
        '200':
          description: "Successfully read feature list"
        '400':
          description: "Failed to read feature list"
    post:
      operationId: 'feature.create'
      tags:
        - 'Feature'
      summary: 'Creates a new feature'
      requestBody:
        description: 'Feature to create'
        required: True
        content:
          application/json:
            schema:
              x-body-name: 'feature'
              $ref: '#/components/schemas/feature'
      responses:
        '201':
          description: 'Feature successfully created'
        '400':
          description: 'Failed to create feature'
  /feature/{trail_feature_id}:
    get:
      operationId: 'feature.retrieve'
      tags:
        - 'Feature'
      summary: 'Reads one specific feature'
      parameters:
        - $ref: '#/components/parameters/trail_feature_id'
      responses:
        '200':
          description: 'Feature read successfully'
    put:
      tags:
        - 'Feature'
      operationId: 'feature.update'
      summary: 'Update feature'
      parameters:
        - $ref: '#/components/parameters/trail_feature_id'
      responses:
        '200':
          description: 'Feature updated successfully'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: 'feature'
              $ref: '#/components/schemas/feature_update'
    delete:
      tags:
        - 'Feature'
      operationId: 'feature.delete'
      summary: 'Deletes a feature'
      parameters:
        - $ref: '#/components/parameters/trail_feature_id'
      responses:
        '204':
          description: 'Feature successfully deleted'
  /trail-feature:
    get:
      operationId: 'trail-feature.read_all'
      tags:
        - 'Trail_Feature'
      summary: 'Reads all trail features'
      responses:
        '200':
          description: 'Successfully read trail feature list'
        '400':
          description: 'Failed to read trail feature list'
    post:
      operationId: 'trail-feature.create'
      tags:
        - 'Trail_Feature'
      summary: 'Creates a new trail feature'
      requestBody:
        description: 'Trail feature to create'
        required: True
        content:
          application/json:
            schema:
              x-body-name: 'trail_feature'
              $ref: '#/components/schemas/trail-feature'
      responses:
        '201':
          description: 'Trail feature successfully created'
        '400':
          description: 'Failed to create trail feature'
  /trail-feature/{id}:
    get:
      operationId: 'trail-feature.retrieve'
      tags:
        - 'Trail_Feature'
      summary: 'Reads one specific trail feature'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'The ID to search'
          required: True
          schema:
            type: string
        - name: 'type'
          in: 'query'
          description: 'Trail ID or Trail Feature ID'
          required: True
          schema:
            type: string
            enum:
              - Trail
              - Feature
      responses:
        '200':
          description: 'Trail feature read successfully'
  /trail-feature/trail/{trail_id}:
    delete:
      operationId: 'trail-feature.delete_trail_id'
      tags:
        - 'Trail_Feature'
      summary: 'Deletes all trails with specific trail id'
      parameters:
        - name: trail_id
          in: path
          required: True
          description: The ID of the trail to delete from the link entity
          schema:
            type: string
      responses:
        '204': 
          description: 'Trail feature successfully deleted'
  /trail-feature/feature/{trail_feature_id}:
    delete:
      operationId: 'trail-feature.delete_trail_feature_id'
      tags:
        - 'Trail_Feature'
      summary: 'Deletes all trails with specific trail feature id'
      parameters:
        - name: trail_feature_id
          in: path
          required: True
          description: The ID of the trail feature to delete from link entity table
          schema:
            type: string
      responses:
        '204': 
          description: 'Trail feature successfully deleted'
  /authenticate:
    post:
      operationId: 'user.authenticate'
      tags:
        - 'User'
      summary: 'Authenticates user'
      requestBody:
        description: 'User authentication'
        required: True
        content:
          application/json:
            schema:
              x-body-name: 'user_authenticate'
              $ref: '#/components/schemas/authenticate'
      responses:
        '200':
          description: 'User authenticated successfully'